# Generated by Django 3.1.13 on 2021-11-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('client_address', models.TextField()),
                ('refers_to', models.CharField(choices=[('PERSONA_NATURAL', 'Persona Natural'), ('PERSONA_JURIDICA', 'Persona Juridica')], max_length=100)),
            ],
            options={
                'ordering': ['client_name'],
            },
        ),
    ]
